version: '3.3'
services:
  api:
    container_name: "api"
    build: 
      context: ./backend
    shm_size: "9gb"
    ports:
      - "4000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn backend.api.server:app --host 0.0.0.0 --reload
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  web:
    container_name: 'web'
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: npm run dev --host
    working_dir: /app

